#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
# Set OWNER/REPO in the generated stages before any GitHub writes.
WIZARD_REPO="${WIZARD_REPO:-}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  local opener rc
  for opener in wslview explorer.exe xdg-open open; do
    if command -v "$opener" >/dev/null 2>&1; then
      if "$opener" "$url" >/dev/null 2>&1; then
        :
      else
        rc=$?
        # Explorer may return 1 after opening a URL through WSL.
        if [[ "$opener" == explorer.exe && "$rc" -eq 1 ]]; then
          note "if the browser did not open, visit it manually: $url"
        else
          warn "couldn't open a browser; visit it manually: $url"
        fi
      fi
      return 0
    fi
  done
  warn "couldn't open a browser; visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || { warn "input ended; stopping setup"; exit 1; }
}

# confirm "question" is a y/N gate; returns success on yes.
# Always use: if confirm "Continue?"; then ...; else note "Skipped"; fi
# A bare call exits on No under set -e. EOF always stops the wizard.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || { warn "input ended; stopping setup"; exit 1; }
  [[ "$reply" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -e "$ENV_FILE" || -L "$ENV_FILE" ]] || return 1
  [[ -f "$ENV_FILE" && ! -L "$ENV_FILE" ]] || return 2
  local line value
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return $?
  [[ -n "$line" ]] || return 1
  value=${line#*=}
  # Decode the literal single-quoted format written by write_env. Never source .env.
  if [[ "$value" == \'*\' ]]; then
    value=${value:1:${#value}-2}
  elif [[ "$value" == *[[:space:]\#\"\'\`\$]* ]]; then
    warn "unsupported existing dotenv syntax for $1; enter the value again" >&2
    return 1
  fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key") || {
    [[ $? -eq 1 ]] || { warn "cannot read $ENV_FILE; stopping setup"; exit 1; }
    current=""
  }
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || { warn "input ended; stopping setup"; exit 1; }
  [[ -z "$input" && -n "$current" ]] && input="$current"
  [[ -n "$input" ]] || { warn "$key is required; stopping setup"; exit 1; }
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key") || {
    [[ $? -eq 1 ]] || { warn "cannot read $ENV_FILE; stopping setup"; exit 1; }
    current=""
  }
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || { warn "input ended; stopping setup"; exit 1; }
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  [[ -n "$input" ]] || { warn "$key is required; stopping setup"; exit 1; }
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp rc last_char
  [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || { warn "invalid dotenv key"; return 1; }
  # Literal single quotes preserve spaces, #, $, double quotes and backslashes.
  # Reject unsupported values before touching the destination.
  if [[ -z "$value" || "$value" == *$'\n'* || "$value" == *$'\r'* || "$value" == *\'* ]]; then
    warn "$key must be nonempty and contain no line breaks or single quotes"
    return 1
  fi
  if [[ -L "$ENV_FILE" || ( -e "$ENV_FILE" && ! -f "$ENV_FILE" ) ]]; then
    warn "$ENV_FILE must be a regular file, not a symlink"
    return 1
  fi
  tmp=$(mktemp "${ENV_FILE}.tmp.XXXXXX") || return 1
  if [[ -e "$ENV_FILE" ]]; then
    if grep -avE "^${key}=" "$ENV_FILE" > "$tmp"; then
      :
    else
      rc=$?
      if (( rc > 1 )); then
        rm -f "$tmp"
        warn "cannot read $ENV_FILE; original preserved"
        return 1
      fi
    fi
  fi
  # Command substitution strips a trailing newline; add one only if missing.
  if ! last_char=$(tail -c 1 "$tmp"); then
    rm -f "$tmp"
    return 1
  fi
  if ! { [[ -z "$last_char" ]] || printf '\n' >> "$tmp"; } ||
     ! printf "%s='%s'\n" "$key" "$value" >> "$tmp" ||
     ! mv "$tmp" "$ENV_FILE"; then
    rm -f "$tmp"
    warn "could not update $ENV_FILE"
    return 1
  fi
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  [[ -n "$value" ]] || { warn "$name is required"; return 1; }
  if ! _require_repo; then
    SKIPPED+=("GitHub secret $name (set WIZARD_REPO to OWNER/REPO, then re-run)")
    return 0
  fi
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --repo "$WIZARD_REPO" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name --repo $WIZARD_REPO)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  [[ -n "$value" ]] || { warn "$name is required"; return 1; }
  if ! _require_repo; then
    SKIPPED+=("GitHub variable $name (set WIZARD_REPO to OWNER/REPO, then re-run)")
    return 0
  fi
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" --repo "$WIZARD_REPO" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

_require_repo() {
  [[ "$WIZARD_REPO" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || {
    warn "WIZARD_REPO must identify OWNER/REPO; skipping this GitHub write"
    return 1
  }
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Sourcing exposes the helpers for isolated tests without running example actions.
if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then return 0; fi

TOTAL_STAGES=1
# Generated wizards must set the intended repository explicitly here.
# WIZARD_REPO="owner/repository"

banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe: API keys"
say "We'll grab your Stripe test keys and store them for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the API keys page, copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"   # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

finish
